- name: Create group "{{ USER }}"
  group:
    name  : "{{ USER }}"
    gid   : 1000
    state : present

- name: Create user "{{ USER }}"
  user:
    name    : "{{ USER }}"
    uid     : 1000
    group   : "{{ USER }}"
    shell   : /usr/bin/zsh
    password: "{{ PASS | password_hash('sha512') }}"

- name: Update sshd
  copy:
    src     : "{{ HOME }}/code/ansible/roles/vps/files/etc/sshd_config"
    dest    : /etc/ssh/sshd_config
    owner   : root
    group   : root
    mode    : '644'
    backup  : yes
    validate: /usr/bin/sshd -T -f %s
  notify:
    - restart sshd
