---
- name: Set hostname on "{{ inventory_hostname_short }}"
  hostname:
    name: "{{ inventory_hostname }}"

- name: Install packages
  apt:
    pkg:
      - neovim
      - zsh
      - zsh-syntax-highlighting
      - stow
      - tmux
      - docker
      - docker-compose
    update_cache: yes
    autoclean   : yes
    autoremove  : yes
  become: yes

- include_tasks: update.yml
- include_tasks: dotfiles.yml
