---
- name: Set correct hostname
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes

- name: Install packages
  apt:
    pkg: "{{ packages }}"
    update_cache: yes
    autoclean   : yes
    autoremove  : yes
  become: yes

- include_tasks: update.yml
- include_tasks: dotfiles.yml
