---
- name: Set hostname on "{{ inventory_hostname_short }}"
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add user "{{ lookup('env', 'USER') }}"
  user:
    name: "{{ lookup('env', 'USER') }}"
    uid: 1000
    group: "{{ lookup('env', 'USER') }}"

- name: Install packages
  apt:
    pkg:
      - neovim
      - zsh
      - zsh-syntax-highlighting
      - tmux
      - nfs-common
    update_cache: yes
    autoclean: yes
    autoremove: yes
  become: yes

- include_tasks: update.yml
